### ISSUE TITLE
未完成冲突

### ISSUE THREAD

**Issue by freeblank** [cocos-creator/smart-merge-tool#4]
这个fire文件也是奇葩，我就给一个节点加了一个脚本组件，然后所有的ID全部变了，简直变态，然后合同事的文件，131个冲突，我就加一个脚本组件，131个冲突，搞笑的么，然后自动合并了55个，剩下76个要自己解决

**Comment by jareguo** [comment]
这是 2.0 的问题吧？我们之后会完善的~ 另外，你可以使用这里的工具来避免 id 改变的情况。

**Comment by jareguo** [comment]
fire 文件不是一个人类友好的格式，它只是为了机器友好设计的，你把它当成二进制文件进行操作就好。之后有时间的话我们会重构为人类友好的试试。
目前阶段，不建议用 fire 文件进行合并，请使用本仓库的工具来合并~

**Comment by ColinCollins** [comment]
目前编辑器每次调用都会更新一部分的无效内容比如： localZOrder 这个属性，但是它目前没有实际意思啦，所以你在合并的时候只能多费费手。
当然如果考虑到减少费时的话，你也可以尝试的使用 replace 设置，直接选择这个属性将其覆盖掉。
![image](https://user-images.githubusercontent.com/35832931/44011049-c6053628-9ee8-11e8-90a5-cb28e9ff27b7.png)
剩余的部分，emmmm， 暂时没有好的解决方案，只能是看你使用的第三方工具是否顺手咯，可以的话，最好把你认为最最最无聊，最最最不好处理的部分截图下来，这样我更新起来也会有针对性。
@freeblank
